bindAddr = "0.0.0.0"
bindPort = 70
#kcpBindPort = 70
quicBindPort = 70

vhostHTTPPort = 71
vhostHTTPSPort = 72

transport.maxPoolCount = 2000
transport.tcpMux = true
transport.tcpMuxKeepaliveInterval = 1
transport.tcpKeepalive = 10
transport.tls.force = false

webServer.addr = "0.0.0.0"
webServer.port = 73
webServer.user = "admin"
webServer.password = "3375Apqberb"
webServer.pprofEnable = false

log.to = "./frps.log"
log.level = "info"
log.maxDays = 3
log.disablePrintColor = false

auth.method = "token"
auth.token = "apqberb"

allowPorts = [
  { start = 10001, end = 50000 }
]

maxPortsPerClient = 8
udpPacketSize = 1500
natholeAnalysisDataReserveHours = 168
